baseURL: http://wei-adrian-woo.netlify.app/
languageCode: en-us
title: Portfolio website for Wei Wu
theme: forty
googleAnalytics: ''
disqusShortname: ''
params:
  banner:
    buttonText: Get Started
    subtitle: |-
#      A RESPONSIVE SITE TEMPLATE DESIGNED BY HTML5 UP
#      AND RELEASED UNDER THE CREATIVE COMMONS.
    title: Hi, my name is Adrian
  blog: {}
  contact:
    address:
      - city: London, W1U 6BR
        country: United Kingdom
        street: Bickenhall Street
        title: Address
    buttonClear: Clear
    buttonSend: Send message
    email:
      - email: wwu.mam2023@london.edu
        title: Email
    enable: yes
    phone:
      - phone: (440) 7536210578
        title: Phone
  custom_css: []
  custom_js: []
  description: Your description
  error404:
    heading: Page couldn't be found
    text: Please visit [this page](/)
  favicon: favicon.ico
  footer:
    copyright: Company Name
    enable: yes
    quicklinks:
      - alt: HTML5 UP
        text: 'Design: '
        url: http://www.html5up.net
    social:
#      - icon: fa-twitter
#        label: Twitter
#        url: http://www.twitter.com
#      - icon: fa-facebook
#        label: Facebook
#        url: http://www.facebook.com
      - icon: fa-instagram
        label: Instagram
        url: http://www.instagram.com/aadrian_woo/
      - icon: fa-github
        label: GitHub
        url: http://github.com/AdrianWooo
      - icon: fa-linkedin
        label: LinkedIn
        url: http://www.linkedin.com/in/wei-wu-a4b238200/
  image: ''
  name: Your name
  navigation:
    button1:
      - name: Get Started
        url: blogs
    button2:
      - name: Log In
        url: '#'
    links:
      - name: Home
        url: '#'
      - name: Blogs
        url: blogs
#      - name: Generic Blog
#        url: blogs/ipsum
#      - name: Elements
#        url: elements.html
    menu: Menu
    subtitle: By HTML5 Up
    title: Adrian
  tiles:
    enable: yes
    showcase:
      - image: lbs.jpg
#        subtitle: Ipsum Dolor Sit Amet
        title: Academic Background
        url: blogs/academic_background
      - image: pic02.jpg
#        subtitle: Career
        title: Career
        url: blogs/Career
      - image: pic03.jpg
        subtitle: Graduate Prediction
        title: Project
        url: blogs/project_graduate
#      - image: pic04.jpg
#        subtitle: 
#        title: Ipsum
#        url: blogs/ipsum
#      - image: pic05.jpg
#        subtitle: Ipsum Dolor Sit Amet
#        title: Consequat
#        url: blogs/ipsum
#      - image: pic06.jpg
#        subtitle: Feugiat Amet Tempus
#        title: Etiam
#        url: blogs/ipsum
  two:
    buttonText: Get Started
    enable: yes
    subtitle: "Nullam et orci eu lorem consequat tincidunt vivamus et sagittis libero.
      \n    Mauris aliquet magna magna sed nunc rhoncus pharetra. \n    Pellentesque
      condimentum sem. In efficitur ligula tate urna. Maecenas laoreet massa vel lacinia
      pellentesque lorem ipsum dolor. \n    Nullam et orci eu lorem consequat tincidunt.
      Vivamus et sagittis libero.\n    Mauris aliquet magna magna sed nunc rhoncus
      amet pharetra et feugiat tempus."
    title: Massa libero
    url: blogs
